### PR TITLE
Website v2

### PR DESCRIPTION
**Pull request by patrick91**

### CODE REVIEW

**Comment by remorses** [comment]
super cool 👍

**Comment by remorses** [comment]
Safari doesn't open it, it happens with the Gatsby site documentation too, try remove unnecesssary plugins

**Comment by patrick91** [comment]
@remorses works for me! what version of Safari are you using? :)

**Comment by remorses** [comment]
probably it is a problem with my safari dev settings, it happens in my mojave and catalina latest versions

**Pull request merged**
