### PR TITLE
Migrate to Next JS

### PR DESCRIPTION
**Pull request by jkimbo**
Migrate from Gatsby to NextJS.

## Notes:

* Only supports using a local docs folder
* Had to move a lot of the static queries from gatsby into a bootstrap script that gets data and stores it into json files
* If you add a new doc file the server will need to be restarted because all the docs are collected at start up

## TODO:

* [ ] Edit on github link
* [ ] SEO headers
* [ ] Additional information block
* [ ] Remark plugins
* [ ] Update readme

### CODE REVIEW

**Comment by jkimbo** [comment]
> Only supports using a local docs folder

@patrick91 do you think this is ok? Do we need to support an equivalent to the `gatsby-source-git` plugin?

**Comment by patrick91** [comment]
oh wow that was quick!

> @patrick91 do you think this is ok? Do we need to support an equivalent to the gatsby-source-git plugin?

so I was thinking of fetching the docs file from github directly, without going through any git remo, that means that getting the docs locally is harder, but doable I think.

so prod version -> docs/pages/basic -> HTTP GET to github.com/strawberry-graphql/strawerry/docs/basic.md 
so local version with local docs -> docs/pages/basic -> file open REPO/docs/basic.md 

does this make sense? what do you think?

**Comment by jkimbo** [comment]
I'm not sure it's worth it to be honest because the docs get deployed to prod from the strawberry repo so you'll always have a copy of the code when you're building it. Why would we need to go and fetch the content from github?

**Comment by patrick91** [comment]
> I'm not sure it's worth it to be honest because the docs get deployed to prod from the strawberry repo so you'll always have a copy of the code when you're building it. Why would we need to go and fetch the content from github?

To be fair I didn't think too much about, I just though SSR would make deploy faster as we wouldn't need to run a build command to download the docs, especially since I want to add versioning and translations.

I think it would also help with previews, as we don't need to run a command to generate the docs but we can do:

https://strawberry.rocks/docs/pr/123/basic

and see them directly :)

**Comment by jkimbo** [comment]
Oh I see what you mean. I was thinking that for the first pass I would just get the site building statically like gatsby. Then we can enhance it with SSR content later. Also I'm not sure what the performance would be like with always fetching the content from Github. I would imagine you would want the core of the docs to be statically generated and then extra parts could be SSR rendered where it's useful. Being able to preview the docs for a PR would be very cool!

**Comment by patrick91** [comment]
> Oh I see what you mean. I was thinking that for the first pass I would just get the site building statically like gatsby. 
Sure that works! I though it was going to take more time to build than going SSR first, but looks like you already did it 💯 

> Then we can enhance it with SSR content later. Also I'm not sure what the performance would be like with always fetching the content from Github. 
I need to check, but I guess we could do SSR + caching the pages, I think next/vercel should allow that, so we only SSR the page once every X hours, since we'll have docs based on releases versions

> I would imagine you would want the core of the docs to be statically generated and then extra parts could be SSR rendered where it's useful. 
This could be an option too 😊

> Being able to preview the docs for a PR would be very cool!
Yes totally :D

**Pull request merged**
